
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqjpeszioxcmfmjttogj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxanBlc3ppb3hjbWZtanR0b2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODAwMTQsImV4cCI6MjA2MjU1NjAxNH0.-ckYhtHMWAnY_qhbTMoBBEIt5uD6zMFIDemRr1NI8a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Fix for background image URL
export const BACKGROUND_IMAGE_URL = "https://i.ibb.co/ZRVky5CT/Pronto-Resposta3.png";
